---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/mastodon
patchesStrategicMerge:
  - mastodon-secret-postgres.yaml
  - mastodon-values-postgres.yaml
  - mastodon-secret-redis.yaml
  - mastodon-values-redis.yaml
