---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/mastodon
patchesStrategicMerge:
  - mastodon-secret-elasticsearch.yaml
  - mastodon-secret-postgres.yaml
  # as long as mastodon doesn't support TLS, we can't use authentification
  # - mastodon-secret-redis.yaml
  - mastodon-secret-secrets.yaml
  - mastodon-values-aws.yaml
