---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/mastodon
patchesStrategicMerge:
  - mastodon-secret-aws.yaml
  - mastodon-secret-secrets.yaml
  - mastodon-values-aws.yaml
