apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mastodon
  namespace: mastodon
spec:
  values:
    postgresql:
      postgresqlHostname: rds.cr4tmfjdkrn8.eu-central-1.rds.amazonaws.com
