apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: mastodon
data:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:Wx4aSB5DkZlrd0Z1aMcHvWqklfTqlLrIEp45UQgLpZCXrtu2UA2/8muG339flq2gvf34acD+JGe6Zv/xqKIAvuEribdz4CKocNjUNb8GCOAGhUG36nr0wN/n0bSzgzjiAKv0TYSqfXId75xpUog6om3t+PiL2O1z9SbYK0wNUD8OKhaBU0wCxLHbDboQ4RO0SUtSf+JFXgByGOQq2NJzDH6hllifUAf8tqcwwQ==,iv:GViAQ3VMFBs4BWBBZKcEzN9gTznrfPjXzs0iYRdJbC0=,tag:oUP6ZrlHAm/mytLEvWCCiw==,type:str]
    OTP_SECRET: ENC[AES256_GCM,data:7dfU6g77CzUisOAly5BTFxOI0bJHoBWINwCPgOgRTJdDSPKj4I1bYlQjBjyGy4VRQkAP5Ui8EcZmWIvPa4B8B9igTwm4NJGFRCmSnD8RjQf3anjyKXUyTiTCXuTj09pDvtHtvd7K7e2OpjDNBkmBgeVYwOv9iNLOa3CMrIGUX1aK0hjplH+juIaTyMuv/OYNXtIiRH6He3gZKSVbtRhtGOFTXRdzn9vMKhd92g==,iv:xl+jdtPzWnF9pQ6fcnm88LTnvUHAvTIMRcLvIPS43gY=,tag:Kajcftni4d7UjtGRxM5+HQ==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:ECfpAYNMrXOKtb3LzZg9Ui9Ao2u2/L2aIV9oFiBvEI0sKTOzNy9JIsQZmvsuygQEXUDyX2piyv5twXWl,iv:OtAj4mEbiJAZt8vgPahJGN40SLiQuJDcE+PokLx/cU4=,tag:SiJyFOIGb5k8gSePMJgbWA==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:EbAjVHEUp4cGicnkmu+cM9vjLpNNyaZ6flWfLUrxv1f5YqatVZtGW2jqhzFDkyw4lHvbmF/awZtfhoA1pHZ/F/8VvWg8KXb7vRA7WreJPjxf4y7hmMIb1gFJwPqGoAj8kQVuk6vKBHpHnTmUfSXkW41RalgwcS1M,iv:FtlHDiCCqt9Wxbj/Yl2uasNcsC1JolbUI+hJ17xTgVw=,tag:5pdyE11D8G5tx2TUgQdoIA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:908023327186:alias/sops
          created_at: "2023-01-02T21:48:31Z"
          enc: AQICAHgoCsPPrbUgWB1/8cZiYiOPdNBO9yeKtXazwq0Hqd5GUAF2gvFttFdZsdROO5Mh1HDCAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMhSanJgOKwxNl7Y8nAgEQgDtMP/kV17842H0O30YU9gBIlAWgnfWU3exlrRABu6SuWa+WC58QtcDXqkSX6aQd98U7GM8cTucAtRZoHQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-02T21:48:31Z"
    mac: ENC[AES256_GCM,data:b6HbtYUPR8/VBB8CTzKDQ6iRSSB0pZxIjHrvUCOQBKbg4lgGPqJI8CqfTXHY5WpLx2vvhXBysQkn7DPU+J1JoTF4Y0IcJ4pyt0nAM/3yQOLy27TYC6AIIyEP7Nwq3ennZLQnt4CqKgoQWq/EZtgDoj3zk7JL3P15Pc9LRjXkQhY=,iv:MulnNP0L+1MwvSwLmcXxxDiMw1h3pYdYPSk2Q0SSB/c=,tag:Ir/brxsGlAiAhxdZqMHCrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
