# Managed by Terraform apps-staging
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: mastodon
data:
    password: ENC[AES256_GCM,data:dIxie6XTfwRBlionfk6wWv2BrUVRyOnxuglRiQ==,iv:zExuQy4DSb8XUpTMhPS//p5vEiT/+7nG32j2Zol392o=,tag:0GqqMWsqgabh6bppJvLJfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-02T00:11:04Z"
    mac: ENC[AES256_GCM,data:qcluus+N9fMiQTtlmYQrN3EmRAFWTmDCmi1XvPd3hfNtc1krfGhAi9je1IUz/xilQ8XZJupc3bpVxVy7mi0Vkc/cQwO0QndhlbG8LLFTHu+2OpfopKBHlM944mOnhpAnPE1FEcE/FQhPdauO21QtlsOliLjzRIuu4Ewfj6wzjY4=,iv:UI8mytvKnSZ6I2CLsXOtHn7KB4+1vGzxQ+KYqXz6LN4=,tag:Ru8JbzBBx9VyeEhCiZUHuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
