# Managed by Terraform apps-staging
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: mastodon
data:
    password: ENC[AES256_GCM,data:S8AsIi5Ii7L50eHf8dKyfcrFUFUPUnNsH/ZYug==,iv:/vyiepmdIMIVgzuuUJNQlOJT+4yW0FnN/kYXw95qITs=,tag:n2vH6o6rzUDDzcnFiKzjVQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:908023327186:key/f24ff2c3-9ef1-4a44-85b7-368769fc747f
          created_at: "2023-01-02T21:44:13Z"
          enc: AQICAHgoCsPPrbUgWB1/8cZiYiOPdNBO9yeKtXazwq0Hqd5GUAHknLDhAA/g3qn85KHEq+YxAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMhJqBRSnmpWIeBL5VAgEQgDu1xDFQSQzpArsLyIqtiHoZ02P4RMWp/CU+ZTEnWvp7NeX1hc6ycQQYKET1fWcpW6ZtJUTzg18Mt/cFyA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-02T21:44:13Z"
    mac: ENC[AES256_GCM,data:OFe6MqioXfHxvu320MQSKK19p28tIaM8E84MaYl7XrZk+i/rVuo7PFeXNceOo5gbRmJpvakYDnpwrCLIE8gYoIUiUalZtMFWFkRVkrWGYmpq7yBj7Eb+05r53sHOFyqV/SP8A84gxwPU+Hkp077sSCOrW/lu9uqFP0NvFRAxZwQ=,iv:u8iyA64ZQfjNqr7INAcPnmZBmFSSDknN8tOymxMCCCc=,tag:UuIn08B2ZPOUEmTo2qhgjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
