# Managed by Terraform apps-staging
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: mastodon
data:
    password: ENC[AES256_GCM,data:JbB2nETZ2x7Pc019lHCR6sUx503OTlGD18tWNw==,iv:FKiRGwFVMRp0qDZAM+5As7WPgR9z8ZNa3L5X0A4pX7M=,tag:wsQJilosS0wwZDCflWBzVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-02T00:18:17Z"
    mac: ENC[AES256_GCM,data:0qlP02gBl1v3iuK1doOS0Zxipv0RwNmV+HWDYhw1vtdbrORO3aGB9hhCLGie4qUPOVz/Rkv6XmeMzNj3f/PCYOctvpHCWw4xUAOXzc3SRL4eQLkSlNEZ6E82/8jQN76FmpBj67gtvoIcqv/X55S7QHvBZzDnkedg9Gg80bYXZGg=,iv:Udy0OHdyIqYlhuw4wSi1CvWZWJXnGT8iAfxmiDrw3Is=,tag:ss8wyZRxdZ/F8qI9RzXVBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
