# Managed by Terraform apps-staging
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch
    namespace: mastodon
data:
    elasticPassword: ENC[AES256_GCM,data:Mnn349FlqCcbtk4eOUQ2IIRARe0=,iv:Rb+VmpHV31Qss8VtSu8rjBgt5DejaDTCBNpbs9MT/u4=,tag:c6h3/ZWMjRL+nY3szmlikw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:908023327186:key/f24ff2c3-9ef1-4a44-85b7-368769fc747f
          created_at: "2023-01-05T21:05:18Z"
          enc: AQICAHgoCsPPrbUgWB1/8cZiYiOPdNBO9yeKtXazwq0Hqd5GUAGmsqhU7c6ziA+nBo4x1UYjAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgDvwdfuYNc69uRn5AgEQgDvyyUFJXpnKyf/zAc/Up6OqEqpgqEA8Omd1S8iPZeHA6uSiA4Ls/DC6XUbwtx/KWlpYfI+JrSyzdxbeEg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-05T21:05:18Z"
    mac: ENC[AES256_GCM,data:+XmSike8DHnDbCJyEBM8e+IyKnAmjhO3eqgg2NlnyqcMjWZkoqTHsmkQ53etcDqmJ6HHHvHRiMZ5c+Sx9nWGt3xRTfpUlciIpwvqHV3crq0GTjP3I8Z78sGwCdIFEA2YDtn/L4AxJ12FxEw+F2ryxfaXcime/nmUUXq2+8BGs/w=,iv:TB/sWCwjOAecN3UfY/jjEoZCaXIyxAw66CDEvKFu6GY=,tag:MUXgI1UJ/PJoYtfLoqbKbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: mastodon
data:
    password: ENC[AES256_GCM,data:wwR2ZvKAVVVUSV0r5bcCt58/vj4tywA/rXghUA==,iv:W1/WaSU04/walqh8dYyxZ22EZsbaI5qZl0bmBU54fYY=,tag:cJmKaWuvHdgnCE4tA8NdLw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:908023327186:key/f24ff2c3-9ef1-4a44-85b7-368769fc747f
          created_at: "2023-01-05T21:05:18Z"
          enc: AQICAHgoCsPPrbUgWB1/8cZiYiOPdNBO9yeKtXazwq0Hqd5GUAGmsqhU7c6ziA+nBo4x1UYjAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgDvwdfuYNc69uRn5AgEQgDvyyUFJXpnKyf/zAc/Up6OqEqpgqEA8Omd1S8iPZeHA6uSiA4Ls/DC6XUbwtx/KWlpYfI+JrSyzdxbeEg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-05T21:05:18Z"
    mac: ENC[AES256_GCM,data:+XmSike8DHnDbCJyEBM8e+IyKnAmjhO3eqgg2NlnyqcMjWZkoqTHsmkQ53etcDqmJ6HHHvHRiMZ5c+Sx9nWGt3xRTfpUlciIpwvqHV3crq0GTjP3I8Z78sGwCdIFEA2YDtn/L4AxJ12FxEw+F2ryxfaXcime/nmUUXq2+8BGs/w=,iv:TB/sWCwjOAecN3UfY/jjEoZCaXIyxAw66CDEvKFu6GY=,tag:MUXgI1UJ/PJoYtfLoqbKbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: redis
    namespace: mastodon
data:
    #ENC[AES256_GCM,data:tphjRdl3KAbuwETc1uMA0RbzyLXpKKEiUm+3E7ooXzPJ4Q==,iv:WFveKxDfuiFIFNiAlKZasH3ey0OahOLjNW652MqZ0OE=,tag:03g9RmV5Wxh5kIrVmGGyyg==,type:comment]
    #ENC[AES256_GCM,data:KkcBz7jGG4gczU/VjZ/Wref2gzgbDGSIJr46h+/4TzhFNZ5jTK/cOf3B18Xydbse2oDnS/oe1tb5gCvZO6nBiwM+8owebFu4ohbyzcXOHg==,iv:Vd62WT+f96UiZacfva9inDwZA3BCC9+qWiIvmdnz67I=,tag:MobHnlez13f52cocm9HpmQ==,type:comment]
    redis-password: ""
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:908023327186:key/f24ff2c3-9ef1-4a44-85b7-368769fc747f
          created_at: "2023-01-05T21:05:18Z"
          enc: AQICAHgoCsPPrbUgWB1/8cZiYiOPdNBO9yeKtXazwq0Hqd5GUAGmsqhU7c6ziA+nBo4x1UYjAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgDvwdfuYNc69uRn5AgEQgDvyyUFJXpnKyf/zAc/Up6OqEqpgqEA8Omd1S8iPZeHA6uSiA4Ls/DC6XUbwtx/KWlpYfI+JrSyzdxbeEg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-05T21:05:18Z"
    mac: ENC[AES256_GCM,data:+XmSike8DHnDbCJyEBM8e+IyKnAmjhO3eqgg2NlnyqcMjWZkoqTHsmkQ53etcDqmJ6HHHvHRiMZ5c+Sx9nWGt3xRTfpUlciIpwvqHV3crq0GTjP3I8Z78sGwCdIFEA2YDtn/L4AxJ12FxEw+F2ryxfaXcime/nmUUXq2+8BGs/w=,iv:TB/sWCwjOAecN3UfY/jjEoZCaXIyxAw66CDEvKFu6GY=,tag:MUXgI1UJ/PJoYtfLoqbKbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
