# Managed by Terraform apps-staging
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: mastodon
data:
    password: ENC[AES256_GCM,data:mRXbRcrJ6NBXeA0s1obiFPiY9qEhHA4D9JPhtw==,iv:JCw+o+j+uOqbA4EchGGH7Jjw+sn7CXfI78JvkZKqEH4=,tag:h+SEFGX9B1TdGZhEKJ8Jaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-01T21:11:17Z"
    mac: ENC[AES256_GCM,data:6elphHLrB3+XkIJ1rSIXwfj7MyxHcFrFAxHvB8jBLcPr3MSdtrvEw0g4QACFVldp4FcEHHZZfnAvRSp7hbgihZKcYpSB7fPffZ0mRT7IkPytjltTpwJjaL0oCYJjju/gMO6TkH/ErqQPK6iFE4iw8Zd7nk9lIAVgLJ1Y6eX6CYg=,iv:7ybhvFHvTR/lFeRq8hkvpDLZrmHhlzqSRLL5H24wiJY=,tag:KMQEs1nmKaUewVOE+yF/PA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
