# Managed by Terraform apps-staging
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: mastodon
data:
    password: ENC[AES256_GCM,data:LN+YQMlgTT3uk3uw5lr+7s0tmAPwFkYlO2yUtA==,iv:83N0hpZWpkrrHILEcbqTldvses15tE7eJ/Imzl8jexo=,tag:hJHR04XaP/VSj3EgaYbcLw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:908023327186:key/f24ff2c3-9ef1-4a44-85b7-368769fc747f
          created_at: "2023-01-02T15:48:00Z"
          enc: AQICAHgoCsPPrbUgWB1/8cZiYiOPdNBO9yeKtXazwq0Hqd5GUAGXQeB2JEocrmXvLsMs2nXEAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMfMtbIJ7/0FZhlwOvAgEQgDvEmH7rGW6z6jGI912zYDY10MhJrazzlO6gFqCLoiOBdlqXJvEKoQA8kLqHAKKdebr6NaUzqXvsqn460A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-02T15:48:01Z"
    mac: ENC[AES256_GCM,data:TcPYFQ+oAaxNfBsFq7cX0KN4MuY5Pb1u1Wc5NcTqSVRBS5tVkzrpsZArFi2Z9QZ3WtMN0XMf2wu8DoE7z4NJfWGzkOBalRewqzzfxttBUdDHDACxeaesmprWR0GQ16C+s1F8CoyB0eMZQSP2pNQrzTsmQlbp9fN45f/NX8d/Xuo=,iv:dA00j2VSmno3pdvcqTWZ2qu8G/tteRxk86ZLMtwMDnY=,tag:bMIrHZhVlHadRhvOmYQnhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
