# Managed by Terraform apps-staging
apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: mastodon
data:
    password: ENC[AES256_GCM,data:MV+q/Hy3vYCkC29yfLEfrvqmte6bdEKOhwLtwg==,iv:4C2oB7bMri+Pzq+FXU6MHoqxF7HkxsQvPX/hv/j3D4I=,tag:KlOSBZAuJAuu27XBjr0Qow==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:908023327186:key/f24ff2c3-9ef1-4a44-85b7-368769fc747f
          created_at: "2023-01-03T22:58:42Z"
          enc: AQICAHgoCsPPrbUgWB1/8cZiYiOPdNBO9yeKtXazwq0Hqd5GUAFyhXqu2nGv/7UZqdPgSV2NAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMI5KZjs7eCiPYCMwiAgEQgDs/MamUkJwT9rJGibVXdkThL0Gy+86h8IeYu1zGbkKN0s5YIBl0+JS1hyGB5d34LDbKTQMPuIobZcEK4w==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-03T22:58:42Z"
    mac: ENC[AES256_GCM,data:X0L5TLHhNROHyCQ9+fgoOhIaGvHtjqnIlUSj4GWclj7cfz9RRSFQou2n1eKfK+ePPopiXx38SDnfQjdMm3vhE485ljmBWIepkkzcGlZlTsOaI0rFwm3HRe1JG/hkC7Yi8iTdzRhe/wyLcO+6s0ZGyy9O4c1u2XVQOazpyxOxl+k=,iv:my1CsBB4d4j3V6b1TmM0x1xk0NHVu4tzJ5AIVhvGdI8=,tag:1nZNvcyYT6TuNy4FKDPG2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
