apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mastodon
  namespace: mastodon
spec:
  values:
    elasticsearch:
      host: vpc-opensearch-7xpebshupfbc75oegbpqq3v24q.eu-central-1.es.amazonaws.com
    postgresql:
      postgresqlHostname: rds.cr4tmfjdkrn8.eu-central-1.rds.amazonaws.com
    redis:
      hostname: redis.pm161k.ng.0001.euc1.cache.amazonaws.com
