---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mastodon
resources:
  - namespace.yaml
  - release.yaml
  - secret-elasticsearch.yaml
  - secret-postgres.yaml
  # as long as mastodon doesn't support TLS, we can't use authentification
  # - secret-redis.yaml
  - secret-secrets.yaml
