---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/staging/aws_eu-central-1
  prune: true
  validation: client
  decryption:
    provider: sops
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: mastodon
      namespace: mastodon
