apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: mastodon
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/jodok/mastodon-chart
  ref:
    branch: main
