apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "6.12.2"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # https://github.com/bitnami/charts/blob/master/bitnami/external-dns/values.yaml
  values:
    serviceAccount:
      create: true  # IRSA role is being created with terraform
      name: external-dns
    provider: aws
    policy: sync  # also delete records after resource removal
    aws:
      region: "eu-west-1"
      zoneType: public
    txtOwnerId:  # kustomization
    domainFilters:  # kustomization
    - example.com
